# Generated by Django 3.2.7 on 2021-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='quantity',
            new_name='maxquantity',
        ),
        migrations.AddField(
            model_name='course',
            name='nowquantity',
            field=models.IntegerField(default=0),
        ),
    ]
